### ISSUE TITLE
No Close-Button in Settings window of Nemo

### ISSUE THREAD

**Issue by Etamuk** [vinceliuice/Mojave-gtk-theme#10]
Hello,

i installed your Mojave theme on my Linux Mint 19.1 Cinnamon system and noticed, there is no Close-Button (X) in the window decoration. Please see my screenshot.

![bildschirmfoto vom 2019-01-25 21-11-22](https://user-images.githubusercontent.com/20098065/51771129-4a25bf00-20e8-11e9-9c07-b16b15dc3565.png)

**Comment by AndhikaWB** [comment]
I'm also using Linux Mint 19.1 Cinnamon. The close, maximize, and minimize button are there. Check the latest version (in case you're still using it). The title bar preview on the 'Themes' app is still empty tho. Maybe will be fixed in future release.

**Comment by vinceliuice** [comment]
Fixed
