### ISSUE TITLE
Chrome mojave-dark-alt white text

### ISSUE THREAD

**Issue by lfelipe1501** [vinceliuice/Mojave-gtk-theme#101]
In 
Mojave-dark
Mojave-dark-alt
Mojave-dark-solid
Mojave-dark-solid-alt

the text in google-chrome is white and the menus too is white:

![image](https://user-images.githubusercontent.com/7816653/73208127-e7f50500-4113-11ea-9f75-6b973c77b71f.png)

**Comment by vinceliuice** [comment]
![Screenshot_20200202_144500](https://user-images.githubusercontent.com/7604295/73604389-f7b89180-45ca-11ea-8125-03a43415dea6.png)

**Comment by vinceliuice** [comment]
Are you using Gnome desktop?

**Comment by lfelipe1501** [comment]
> Are you using Gnome desktop?

yes, i'm using gnome desktop why?

![Screenshot from 2020-02-04 14-54-11](https://user-images.githubusercontent.com/7816653/73781577-7e51a800-475e-11ea-8b54-1bfb5562fbad.png)

**Comment by vinceliuice** [comment]
I'm using gnome 3.34.2 of manjaro, but I don't have this issue, maybe you can download the last update on github and reinstall this theme

**Comment by lfelipe1501** [comment]
All done now 😅
