### ISSUE TITLE
Theme broken when scaling is change

### ISSUE THREAD

**Issue by sapjunior** [vinceliuice/Mojave-gtk-theme#104]
As shown in this picture, theme will be broken after screen scaling or resolution is change (internal screen resolution is not equal to external screen) unless relogin or restart is applied. Is there anyway to fix this problem?

![Screenshot from 2020-02-02 08-44-08](https://user-images.githubusercontent.com/987946/73601709-cfb03a80-4598-11ea-99b9-9b0426516019.png)
![Screenshot from 2020-02-02 08-48-57](https://user-images.githubusercontent.com/987946/73601713-de96ed00-4598-11ea-84bb-ab8d52f25031.png)

**Comment by vinceliuice** [comment]
run  "atl + f2" put a " r " on the popup entry, then cilck "enter", this will restart gnome-shell without relogin or reboot your system.

**Comment by sapjunior** [comment]
Seems to be GNOME problems. Thank you!
