### ISSUE TITLE
一些不太显眼的小问题

### ISSUE THREAD

**Issue by SQ-Duan** [vinceliuice/Mojave-gtk-theme#108]
## Environment

OS: Ubuntu 18.04
Themes:
- Applications: Mojave-dark-solid
- Cursor: DMZ-Black
- Icons: Papirus-Adapta
- Shell: Mojave-dark-solid

## Problem

1. 当本地语言设置为英语en-US时，点顶栏中间的时间时，弹出的日历日期显示不完整，比如今天是2020年2月18日，日历显示为`February 18 20...`，稍微再加宽一点应该就可以了， 建议调整css时把系统时间调到九月，因为September是月份单词里字母最多最长的；

2. 打开Ubuntu Software -> Add-ons -> Shell Extensions后，界面中有些栏的背景颜色和字体颜色接近，导致看不清。

**Comment by vinceliuice** [comment]
有截图吗，给我发几个截图吧，我大看明白在哪

**Comment by SQ-Duan** [comment]
![image](https://user-images.githubusercontent.com/20452743/74824620-6758ab80-5343-11ea-8467-b9f8b3f6cf11.png)
这个我把`.datemenu-today-button .date-label`的font-szie改为17pt后可以完全显示。

![image](https://user-images.githubusercontent.com/20452743/74824737-a5ee6600-5343-11ea-946b-eb5efc98304d.png)
第二副是ubuntu应用商店的，不知道对应哪个class/id

**Comment by vinceliuice** [comment]
中文可以显示全，其他问题我会试着全修复了

**Comment by LittleFatHero** [comment]
> 中文可以显示全，其他问题我会试着全修复了

我想问一下，如果我系统是GTK+ 3.20 or later，还需要安装gtk-murrine-engine和gtk2-engines这两个东西么？这两个东西是不是只有GTK 2的系统才需要安装？

**Comment by vinceliuice** [comment]
只要你用得到gtk2的程序的话还是需要的，像inscape和gimp等都是gtk2程序
