### ISSUE TITLE
Very stretched menu in gnome-screenshot

### ISSUE THREAD

**Issue by Etamuk** [vinceliuice/Mojave-gtk-theme#11]
Hello,

in Linux Mint Cinnamon 19.1 the default screenshot program is gnome-screenshot. After taking a screenshot a dialog window appers. In this window a drop down menu is stretched. Please see my screenshot.
![bildschirmfoto speichern_001](https://user-images.githubusercontent.com/20098065/51771280-d506b980-20e8-11e9-801a-fb7e22de2979.png)

**Comment by vinceliuice** [comment]
This is because the icon on the combo button is too big, change the icon theme and this will change too
