### ISSUE TITLE
debian10 gdm不可以用

### ISSUE THREAD

**Issue by DonjuanXX** [vinceliuice/Mojave-gtk-theme#111]
按照https://www.youtube.com/watch?v=VCvSjDnKI_s安装gdm，
When I run “sudo dpkg-reconfigure gdm3”  nothing happened, just open new command line, what is wrong?
OS: Debian 10 buster

**Comment by vinceliuice** [comment]
给我看一下你的usr/share/gnome-shell/目录吧

**Comment by DonjuanXX** [comment]
gnome-shell目录下：
extensions                             Gvc-1.0.gir          Shell-0.1.gir
gnome-shell-dbus-interfaces.gresource  modes                ShellMenu-0.1.gir
gnome-shell-osk-layouts.gresource      perf-background.xml  St-1.0.gir
gnome-shell-theme.gresource            search-providers     theme
theme目录下：
calendar-today.svg           classic-toggle-on-us.svg
classic-process-working.svg  gnome-classic.css
classic-toggle-off-intl.svg  gnome-classic-high-contrast.css
classic-toggle-off-us.svg    ubuntu.css
classic-toggle-on-intl.svg
//感谢回复

**Comment by vinceliuice** [comment]
我更新啦一下你可以下载最新的试试

**Comment by DonjuanXX** [comment]
很抱歉，试了几次还是没有效果，有什么相关的log可以提供给你方便排查吗？

**Comment by Hoking007** [comment]
我之前用Manjaro可以切换gdm，最近用ubuntu 18.04无法切换gdm风格
请问有什么log可以提供排查吗？

**Comment by vinceliuice** [comment]
你是用哪条命令切换的？
我记得不一样的

**Comment by Hoking007** [comment]
我都是用“README.md”中介绍的命令：
sudo ./install.sh -g

**Comment by vinceliuice** [comment]
我更新了一下，大家可以试试新版能安装吗？

**Comment by Hoking007** [comment]
> 我更新了一下，大家可以试试新版能安装吗？

Installing Ubuntu gnome-shell theme...
ln: 无法创建符号链接'gdm3.css': 文件已存在

**Comment by vinceliuice** [comment]
这个没事，安装第二遍的时候会提示已经有链接了，因为第一次就创建好了，不影响的

**Comment by Hoking007** [comment]
重启电脑后看到新的gdm了，不过没有壁纸



---原始邮件---
发件人: "Vince"<notifications@github.com&gt;
发送时间: 2020年3月19日(周四) 晚上7:02
收件人: "vinceliuice/Mojave-gtk-theme"<Mojave-gtk-theme@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Hoking"<41755982@qq.com&gt;;
主题: Re: [vinceliuice/Mojave-gtk-theme] debian10 gdm不可以用 (#111)




 
这个没事，安装第二遍的时候会提示已经有链接了，因为第一次就创建好了，不影响的

**Comment by vinceliuice** [comment]
我再测试测试，看哪出错啦

**Comment by vinceliuice** [comment]
我下了个ubuntu18.04试啦好多遍，发现这个版本的ubuntu，gdm主题只使用usr/share/gnome-shell/theme 里的ubuntu.css文件，不能使用其他的文件，而我的主题好多元素比如菜单背景和登录背景都是图片素材放在assets目录里，但即便我复制到和ubuntu.css同一个目录主题也使用不了，所以这个版本的ubuntu或者debian就只能使用一些不用图标素材的主题了，

**Comment by Hoking007** [comment]
哦，原来是这样哈。这套主题在xfce4下也能很好的表现，配合作者的图标主题，比其他主题和图标精细更有高级感！非常感谢vinceliuice！

---原始邮件---
发件人: "Vince"<notifications@github.com&gt;
发送时间: 2020年3月19日(周四) 晚上11:46
收件人: "vinceliuice/Mojave-gtk-theme"<Mojave-gtk-theme@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Hoking"<41755982@qq.com&gt;;
主题: Re: [vinceliuice/Mojave-gtk-theme] debian10 gdm不可以用 (#111)




 
我下了个ubuntu18.04试啦好多遍，发现这个版本的ubuntu，gdm主题只使用usr/share/gnome-shell/theme 里的ubuntu.css文件，不能使用其他的文件，而我的主题好多元素比如菜单背景和登录背景都是图片素材放在assets目录里，但即便我复制到和ubuntu.css同一个目录主题也使用不了，所以这个版本的ubuntu或者debian就只能使用一些不用图标素材的主题了，

**Comment by DonjuanXX** [comment]
抱歉,在重新安装之后报了如下很多错误,重启之后原来的命令行(application)主题已经已经无法使用(透明),且gdm无变化(sudo dpkg-reconfigure gdm3无反映),仅取一些错误列下: 
打开应用时时错误Gtk-WARNING **: 22:39:43.425: Theme parsing error: gtk.css:1:58: Failed to import: The resource at “/org/gnome/Mojave-theme/gtk.css” does not exist
运行 sudo ./install.sh --gdm 出现的问题(有省略)
./parse-sass.sh: line 5: has_command: command not found
./parse-sass.sh: line 7: has_command: command not found
./parse-sass.sh: line 9: has_command: command not found
./parse-sass.sh: line 11: has_command: command not found
./parse-sass.sh: line 13: has_command: command not found
./parse-sass.sh: line 32: sassc: command not found

==> Generating the gnome-shell-dark-solid.css...
./parse-sass.sh: line 36: sassc: command not found
==> Generating the cinnamon-dark-solid.css...
inkscape and optipng needs to be installed to generate the assets.
./render-assets.sh: line 11: has_command: command not found
./render-assets.sh: line 13: has_command: command not found
./render-assets.sh: line 15: has_command: command not found
./render-assets.sh: line 17: has_command: command not found
./render-assets.sh: line 19: has_command: command not found

Rendering assets-light/arrow-down.png
./render-assets.sh: line 24: /usr/bin/inkscape: No such file or directory

Installing '/usr/share/themes/Mojave-light'...
cp: cannot stat '/home/mason/Downloads/Mojave-gtk-theme-master/src/main/gnome-shell/gnome-shell-light.css': No such file or directory
cp: cannot stat '/home/mason/Downloads/Mojave-gtk-theme-master/src/assets/gtk-3.0/thumbnail-light.png': No such file or directory
cp: cannot stat '/home/mason/Downloads/Mojave-gtk-theme-master/src/main/gtk-3.0/gtk-dark.css': No such file or directory
cp: cannot stat '/home/mason/Downloads/Mojave-gtk-theme-master/src/main/gtk-3.0/gtk-light.css': No such file or directory

**Comment by vinceliuice** [comment]
@DonjuanXX 你没有安装依赖所以会这样，还有gnome3.34以前的版本shell主题不要用最新的，不像gtk主题可以向下版本兼容并且3.20之后的版本都改动不大，但shell版本最近改动都很大，建议你shell主题的话单独用这个版本的比较好：https://github.com/vinceliuice/Mojave-gtk-theme/releases/tag/2019-09-09

**Comment by DonjuanXX** [comment]
请问需要安装什么依赖?

**Comment by DonjuanXX** [comment]
gtk-themes更新后已修复

**Comment by vinceliuice** [comment]
Depends requirment
1.     sassc.
2.     optipng.
3.     inkscape.
4.     libglib2.0-dev. 
5.     libxml2-utils.
