### ISSUE TITLE
url bar prosition and it's dropdown background not working. [Firefox 75.0b2]

### ISSUE THREAD

**Issue by mrabirahamed** [vinceliuice/Mojave-gtk-theme#114]
Firefox's URL bar is not in the correct position. A little below the actual position in the Open tab, it goes up a little while writing in the URL bar and the background is not working properly.
Issue 1:
![Screenshot from 2020-03-12 11-39-00](https://user-images.githubusercontent.com/34349365/76490976-b4b5cd80-6456-11ea-8d21-a1cd896ca295.png)

Issue 2:
[Screencast_03-12-2020_11:40:36 AM.zip](https://github.com/vinceliuice/Mojave-gtk-theme/files/4322451/Screencast_03-12-2020_11.40.36.AM.zip)

**Comment by vinceliuice** [comment]
Fixed!

**Comment by mrabirahamed** [comment]
thank you very much
