### ISSUE TITLE
这些都是在gnome3.3.6上的bug

### ISSUE THREAD

**Issue by LokeyZ** [vinceliuice/Mojave-gtk-theme#115]
![52BC62EFBABED45A7354D192DE3F7803](https://user-images.githubusercontent.com/54281485/76492177-8b9f3800-646a-11ea-8cd6-4b20f0dc567b.jpg)
![D78223801F3526C502EC48FC4D49E049](https://user-images.githubusercontent.com/54281485/76492183-8f32bf00-646a-11ea-9af5-fca755c3ef68.jpg)

[this is a video.zip](https://github.com/vinceliuice/Mojave-gtk-theme/files/4322505/this.is.a.video.zip)

**Comment by vinceliuice** [comment]
最新版已经修复了！

**Comment by LokeyZ** [comment]
好的，谢谢，还是你勤快，gnome desktop的团队都没你那么勤快，真的，他们dock栏都做了几年了，现在依旧是那么鸡肋，提交个人意见就没人理过

**Comment by vinceliuice** [comment]
哈哈， 外国人的效率哪有咱中国人高啊！

**Comment by LokeyZ** [comment]
> 哈哈，过奖啦，不过确实，外国人的效率哪有咱中国人高啊！

我对自带的dock栏啊，可以说是恨到入骨，默认只能在左边停放，还不是直接显示停靠在桌面那种，必须要按win那个键打开活动窗口才能见到它，想要找到软件还得点软件入口图标，就跟套娃一样，用dash to dock吧，gnome一更新，它必死，用plank dock吧，它又不像dash to dock那样有软件入口。而且自带的还有放的图标越多，图标就会越变越小，小到你都要靠近屏幕才能看清楚了。这个问题我在gnome的官方推特上提了3年，压根没人理，到现在都还是老样子

**Comment by vinceliuice** [comment]
gnome一直都这样老是往触屏上去优化，不注重pc的用户体验，一意孤行，简洁倒是挺简洁的，就是必要功能缺失很蛋疼

**Comment by vinceliuice** [comment]
gnome一直都这样老是往触屏上去优化，不注重pc的用户体验，一意孤行，简洁倒是挺简洁的，就是必要功能缺失很蛋疼

**Comment by LokeyZ** [comment]
> gnome一直都这样老是往触屏上去优化，不注重pc的用户体验，一意孤行，简洁倒是挺简洁的，就是必要功能缺失很蛋疼

确实，有时候我都想换成kde，但是又觉得kde那个软件显示方式有点不习惯

**Comment by vinceliuice** [comment]
kde就是有点乱，这两个桌面要是可以综合一下取长补短就完美了!
