### ISSUE TITLE
还是有个小bug

### ISSUE THREAD

**Issue by LokeyZ** [vinceliuice/Mojave-gtk-theme#116]
![AE333A9C203E9BB6B638FD97CA6068E4](https://user-images.githubusercontent.com/54281485/76506143-a501ad80-6485-11ea-8b4d-607b81e281bb.jpg)

**Comment by vinceliuice** [comment]
这个bug我感觉是shell自己的bug，因为系统自带的主题都有这个问题，我目前还没找到修复的方法

**Comment by vinceliuice** [comment]
我再试试吧

**Comment by LokeyZ** [comment]
> 这个bug我感觉是shell自己的bug，因为系统自带的主题都有这个问题，我目前还没找到修复的方法
这带的shell没有重叠的问题

**Comment by LokeyZ** [comment]
![7086CA0B14ACDFFB82FE0CD3C7BA3629](https://user-images.githubusercontent.com/54281485/76521622-2403df80-64a0-11ea-96f7-43c4d69be757.jpg)

**Comment by vinceliuice** [comment]
更新啦一下，没找到什么好方法，只能给菜单每项上下都加点空间了

**Comment by vinceliuice** [comment]
现在看起来应该好一点

**Comment by LokeyZ** [comment]
解决了，官方的做法也是提高高度。官方那个主题也是通过提高高度来解决的

**Comment by vinceliuice** [comment]
好吧，希望官方能直接去掉这行，又没用
