### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by ArchFeh** [vinceliuice/Mojave-gtk-theme#119]
`./install.sh -i arch`
``` compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details. 

依赖都已安装

**Comment by vinceliuice** [comment]
我看看，你的系统版本是什么啊？

**Comment by vinceliuice** [comment]
我更新啦一下， 好像sassc有一些特性不再支持啦，你现在再试一下

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/Mojave-gtk-theme/releases/tag/2020-03-19
我添加了编译后的压缩包，你也可以直接下载这个

**Comment by ArchFeh** [comment]
> 我看看，你的系统版本是什么啊？

系统是archlinux Linux archie 5.5.10-arch1-1 #1 SMP PREEMPT Wed, 18 Mar 2020 08:40:35 +0000 x86_64 GNU/Linux
好像还是无法编译，直接下载编译后的好了。。

**Comment by vinceliuice** [comment]
嗯。我用的manjaro，包没这么新，基于arc主题制作的估计代码有点老啦，得更新一下了

**Comment by ArchFeh** [comment]
> 嗯。我用的manjaro，包没这么新，基于arc主题制作的估计代码有点老啦，得更新一下了

嗯嗯,可能是我太激进了,test开的飞起..直接用你编译过的就好了...感谢你的工作,让人耳目一新心旷神怡)))

**Comment by vinceliuice** [comment]
😁不客气！

**Comment by ArchFeh** [comment]
突然发现是我的错觉吗，你给的release solid和普通版的gnome shell都是实心的，我记得以前shell是有透明的吧？

**Comment by vinceliuice** [comment]
我回去检测一下，可能安装脚步的问题

**Comment by vinceliuice** [comment]
之前不小心把panel的透明度去掉啦，这次修复了， 更换了release的压缩包，你下载新的试试

**Comment by ArchFeh** [comment]
好啦再次赏心悦目！

**Comment by ArchFeh** [comment]
之前直接clone了就能用，可以赶上每次的更新。现在需要自编译，像我这种没法自编译的只能等你每次的release吗？考虑维护一个aur包吗？

**Comment by vinceliuice** [comment]
考虑到包包越来越大，而且国内网速又不行，所以很多网友建议我降低github的体积，能自己编译的就不放github里了，以后有大更新的时候都会上release的，有时间会考虑学一下aur打包

**Comment by ArchFeh** [comment]
好的。。我试试看无法编译的情况能不能解决

**Comment by vinceliuice** [comment]
有个网友也是arch gnome 3.36 版本，他编译成功了，但是使用主题桌面会崩溃，看来我有必要搞个arch测试一下了

**Comment by ArchFeh** [comment]
arch欢迎你，喜大普奔😁

**Comment by vinceliuice** [comment]
😁️ 时隔多年没安装arch了，不知道还能不能安装成功

**Comment by ArchFeh** [comment]
不会的可以直接问，手把手教学😆造福aur，利在千秋，让大家都能用上美美的主题

**Comment by vinceliuice** [comment]
好的， 现在正对着wiki操作laughing

**Comment by vinceliuice** [comment]
bug修复啦，现在最新版也能编译了！

**Comment by ArchFeh** [comment]
立刻试了一下,果然可以了!👍

**Comment by ArchFeh** [comment]
修改了一下aur里<a href>https://aur.archlinux.org/packages/mojave-gtk-theme-git>主题</a>的pkgbuild,应该可以正常安装了,我看他好像没在维护了,我可以接手看看.

**Comment by vinceliuice** [comment]
那非常感谢了，我目前得把我所有主题的bug都修复了，自己确实也没时间管理各平台的安装包，有人替我维护最好不过了

**Comment by ArchFeh** [comment]
恩，你专心改bug就行。目前发布了gnome 3.36和kde 5.18确实很多改动。

**Comment by vinceliuice** [comment]
嗯，gnome-shell改动挺大的

**Comment by ArchFeh** [comment]
打包成功了，你可以放在github的readme上，让别人直接移步AUR或者手动克隆编译。，<a href="https://aur.archlinux.org/packages/mojave-gtk-theme-git-new/">AUR</a>

**Comment by vinceliuice** [comment]
好的，非常感谢！

**Comment by ArchFeh** [comment]
应用程序图标点了之后就消失了，dark主题+mojave circle dark图标下https://sm.ms/image/YVoczGTtHnA5Rhp

**Comment by vinceliuice** [comment]
这个问题最新版应该修复了

**Comment by ArchFeh** [comment]
./install.sh 
./install.sh: line 22: syntax error near unexpected token `('

**Comment by ArchFeh** [comment]
22行少了个')"

**Comment by vinceliuice** [comment]
失误，现在更新了

**Comment by ArchFeh** [comment]
另，编译时是否有多线程的选项？目前直接使用脚本好像有点慢，每次更新等好久

**Comment by vinceliuice** [comment]
这个我技术搞不了，我只知道写基本的脚本

**Comment by ArchFeh** [comment]
行，我去研究下，应该有

**Comment by vinceliuice** [comment]
你用github-desktop fork一份更新可以以后快一些，因为像图片素材这些只要第一次创建了以后就直接跳过了，只有css文件需要编译

**Comment by vinceliuice** [comment]
因为有个.gitignore文件把编译后的文件和文件夹忽略了，所以这些文件的变化不影响的

**Comment by ArchFeh** [comment]
恩，但是对于aur的用户，每次都得重新渲染一遍的

**Comment by vinceliuice** [comment]
那个确实

**Comment by ArchFeh** [comment]
把原来的new包合并到了mojave-gtk-theme-git，https://aur.archlinux.org/packages/mojave-gtk-theme-git

**Comment by vinceliuice** [comment]
好的！

**Comment by ArchFeh** [comment]
最新的commit用install_test也编译不过，因为src/main/gnome-shell/gnome-shell-light.css找不到，源文件已成为.scss

**Comment by vinceliuice** [comment]
@ArchFeh 用install.sh，不要用那个文件，那是我自己测试的时候用的文件
