### ISSUE TITLE
Apple icon in GNOME Shell

### ISSUE THREAD

**Issue by paulcarroty** [vinceliuice/Mojave-gtk-theme#12]
@vinceliuice, I'd recommend to replace it 'cause

* it's not legal
* looks like cheap Chinese fake
 
I use the GNOME icon, looks great.
![header](https://user-images.githubusercontent.com/1550705/52407776-145dde80-2ac9-11e9-92fd-9c24bda9c69c.png)

[activities.zip](https://github.com/vinceliuice/Mojave-gtk-theme/files/2975495/activities.zip)

**Comment by vinceliuice** [comment]
I'll give a option at future update for other activities icon

**Comment by hayspat** [comment]
My svg files for gnome if anyone need it
https://svgshare.com/s/CZG  (dark)
https://svgshare.com/s/CZW (light)

**Comment by paulcarroty** [comment]
Great share!

@vinceliuice can you add a CLI option to choose different icons? Apple, GNOME, Xfce, Microsoft whatever. And maybe corporate-free will be great too.

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
@paulcarroty  Now you can use ./install.sh -i ubuntu or ./install.sh -i gnome to install different icons of gnome-shell

**Comment by vinceliuice** [comment]
Use ./install -h to see supported icons

**Comment by paulcarroty** [comment]
Thanks @vinceliuice!

**Comment by vinceliuice** [comment]
You are welcome!

**Comment by ShubhamDubey** [comment]
I'm getting two icons, How can I fix it?
![Screenshot from 2019-11-02 00-33-24](https://user-images.githubusercontent.com/10476663/68049803-c9948e80-fd09-11e9-8d9d-7124911b518c.png)

**Comment by vinceliuice** [comment]
@ShubhamDubey you can try run `sudo ./install.sh -g` to install gdm theme replace the default gnome-shell theme
