### ISSUE TITLE
需要安装libglib2.0-dev才能运行install.sh中的glib-compile-resources指令

### ISSUE THREAD

**Issue by Hoking007** [vinceliuice/Mojave-gtk-theme#120]
运行最新install.sh遇到这个问题，可以提醒用户安装libglib2.0-dev以获得glib-compile-resources指令

**Comment by Hoking007** [comment]
还需要安装libxml2-utils

**Comment by vinceliuice** [comment]
好的，谢谢提醒！

**Comment by Hoking007** [comment]
还有一个问题：
Failed to open file “/home/hoking/work/projects/github/themes-git/Mojave-gtk-theme/src/gnome-shell/gnome-shell-theme.gresource.xml”: 没有那个文件或目录
仓库是最新的，是不是缺少一个文件？

**Comment by vinceliuice** [comment]
忘了修改脚本里的路径了，现在这个文件在这个位置https://github.com/vinceliuice/Mojave-gtk-theme/blob/master/src/main/gnome-shell/gnome-shell-theme.gresource.xml

**Comment by vinceliuice** [comment]
我回去测试一下gdm主题，会把这些问题修复的

**Comment by Hoking007** [comment]
> 我回去测试一下gdm主题，会把这些问题修复的

非常感谢！
太喜欢这个主题和图标！

**Comment by vinceliuice** [comment]
不客气！

**Comment by vinceliuice** [comment]
对了，我想问一下你的是什么系统啊，是fedora吗？

**Comment by Hoking007** [comment]
> 对了，我想问一下你的是什么系统啊，是fedora吗？

我现在是ubuntu 18.04，用gdm有问题
之前是manjaro，用gdm没问题

**Comment by vinceliuice** [comment]
好的，我电脑里有个ubuntu20.04, 我先测试一下吧

**Comment by Hoking007** [comment]
> 好的，我电脑里有个ubuntu20.04, 我先测试一下吧

你真先进：）都拿到20.04了哈

**Comment by Hoking007** [comment]
> 好的，我电脑里有个ubuntu20.04, 我先测试一下吧

如果需要，我可以帮你验证，不过我刚切换到xfce4，用的也是你的主题

**Comment by vinceliuice** [comment]
我更新了一下， 你试试现在能安装gdm主题了没，不过我是在20.04上试的，ubuntu20.04没问题了
