### ISSUE TITLE
Gnome freeze

### ISSUE THREAD

**Issue by BogdanDarius** [vinceliuice/Mojave-gtk-theme#121]
Installing is successful, but when I select the theme gnome freezes.

**Comment by jozsr** [comment]
Second that. Gnome freezes instantly.

**Comment by R0b1ns** [comment]
Can you tell me which Linux and Version you have?

I just tested it on a clean Debian 10.3 (Buster) Gnome install. It worked without problems.

This were the required dependencies:

`sudo apt install sassc optipng inkscape libcanberra-gtk-module libglib2.0-dev`

(and 'git')

Installed with:

`sudo ./install.sh -i debian -g`

**Comment by BogdanDarius** [comment]
Arch linux
Kernel 5.5.10
Gnome 3.36

**Comment by pschyma** [comment]
Same here on Arch. Installed via AUR git package. 

It seems to be related to sass. With libsass 3.6.2 the build did not finish after hours, but only 2 warnings were emitted related to compound extension of classes. After an update to 3.6.3 sass emitted many warnings but finished.

The AUR package then installs 1500 MB of files. Gnome is not frozen, but the system is under heavy load (each core @ 100% occupied by different Gnome processes).

**Comment by vinceliuice** [comment]
@pschyma I updated all scss files to support libsass 3.6.2, now it can be built on Arch last version
