### ISSUE TITLE
这是有意为之，还是有bug？

### ISSUE THREAD

**Issue by CNMan** [vinceliuice/Mojave-gtk-theme#123]
全部程序的图标

鼠标悬停前
![Screenshot from 2020-03-20 14-21-33](https://user-images.githubusercontent.com/8692234/77141087-a733bf80-6ab6-11ea-81c6-7a450d75aa17.png)
鼠标悬停后
![Screenshot from 2020-03-20 14-21-36](https://user-images.githubusercontent.com/8692234/77141089-a8fd8300-6ab6-11ea-9414-c8cf21456398.png)

**Comment by vinceliuice** [comment]
你的gnome-shell是早期版本吗，这应该是主题bug，在gnome3.34和3.36没这个问题

**Comment by CNMan** [comment]
> 你的gnome-shell是早期版本吗，这应该是主题bug，在gnome3.34和3.36没这个问题

```
gnome-shell.x86_64                                    3.32.2-9.el8                                       @AppStream
```

**Comment by vinceliuice** [comment]
修复了应该
