### ISSUE TITLE
alt titilebutton variants

### ISSUE THREAD

**Issue by gaou-piou** [vinceliuice/Mojave-gtk-theme#124]
how to use alt titilebutton variants?

**Comment by algent-al** [comment]
alt titlebutton has been [removed](https://github.com/vinceliuice/Mojave-gtk-theme/commit/162e06d381de3130d8509c2fdc4b144b25dccb81).  
The questions is if it will be included again?

**Comment by vinceliuice** [comment]
I‘ll support it soon

**Comment by algent-al** [comment]
I package this theme for [Solus](https://dev.getsol.us/source/mojave-gtk-theme/). But for sure this is a massive [change](https://hasteb.in/fobesiza.xml). Looking forward for alt variant.

**Comment by algent-al** [comment]
Thank you for adding back alt version.

**Comment by gaou-piou** [comment]
Can we have size (small/normal) too?

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
It's ok!
