### ISSUE TITLE
a ui bug with gnome 3.36

### ISSUE THREAD

**Issue by dr3mro** [vinceliuice/Mojave-gtk-theme#128]
![menu](https://user-images.githubusercontent.com/1246089/77734837-1ad35080-7012-11ea-9b65-75756ddf91da.png)
using latest gnome with master branch of your theme the separator looks odd in all context menus 
please fix this

**Comment by vinceliuice** [comment]
Are you using the last version on github?

**Comment by vinceliuice** [comment]
Fixed
