### ISSUE TITLE
Firefox themes on Windows

### ISSUE THREAD

**Issue by Atchess** [vinceliuice/Mojave-gtk-theme#129]
I had tried it on windows.  but something is wrong.  I can't open firefox when I use userchrome. css.  I think it may be because the theme of Firefox depends on the system theme of Linux.  Due to my limited ability, I didn't find related dependencies. Could you help me solve this problem, or can you tell me where these related things are? Thanks！

**Comment by dr3mro** [comment]
this theme is targeting linux  based systems
