### ISSUE TITLE
Nautilus path bar issues in dark version

### ISSUE THREAD

**Issue by Dvlnst** [vinceliuice/Mojave-gtk-theme#131]
Hi, I updated your theme from the current master and I noticed a couple of issues:

**1. Color in current tab:**
![Screenshot from 2020-03-29 20-19-07](https://user-images.githubusercontent.com/36289254/77856926-c808bd00-71fa-11ea-97f2-2d33cc821576.png)
![Screenshot from 2020-03-29 20-32-46](https://user-images.githubusercontent.com/36289254/77857240-9db7ff00-71fc-11ea-930b-8592d313af9f.png)

**2. Straight corners when tab is selected:**
![Screenshot from 2020-03-29 20-19-25](https://user-images.githubusercontent.com/36289254/77857007-70b71c80-71fb-11ea-8498-17a33c65aa8f.png)

I hope it helps.

Kind regards.

**Comment by vinceliuice** [comment]
Are you using the last version on github?

**Comment by Dvlnst** [comment]
Yes, I'm using the current master. I tried again now but issues remain.

**Comment by docquantum** [comment]
@Dvlnst what's your system? I'm on gnome 3.36 and don't have that issue on the current master.

**Comment by Dvlnst** [comment]
I'm using Debian 10 with Gnome Shell 3.30.2.

**Comment by vinceliuice** [comment]
Fixed

**Comment by Dvlnst** [comment]
Thank you for the quick support.
