### ISSUE TITLE
Big toggle button on new "Extensions" app

### ISSUE THREAD

**Issue by brneor** [vinceliuice/Mojave-gtk-theme#135]
![gnome-shell-screenshot-P3GRI0](https://user-images.githubusercontent.com/5962898/78610157-a468f680-783a-11ea-9b25-330fb1a07546.png)

The button is very different from what we have on "Tweaks" app:

![Screenshot-20200406191350-1134x700](https://user-images.githubusercontent.com/5962898/78610233-cebab400-783a-11ea-8be1-78c97d633253.png)

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by vinceliuice** [comment]
Fixed

**Comment by brneor** [comment]
Thank you for your amazing work on this theme.

**Comment by vinceliuice** [comment]
You are welcome!
