### ISSUE TITLE
fail to export resource with latest inkscape

### ISSUE THREAD

**Issue by gayanper** [vinceliuice/Mojave-gtk-theme#140]
This is due to removal of --export-png option which was deprecated
https://wiki.inkscape.org/wiki/index.php/Using_the_Command_Line

**Comment by vinceliuice** [comment]
I updated the shell, now it'll works on Fedore or Manjaro

**Comment by pschyma** [comment]
This change breaks the build on Arch.

Here I have: `extra/inkscape 0.92.5-1 (16.3 MiB 124.0 MiB) (Installed)` which doesn't know about `--export-type=png`:
`extra/inkscape 0.92.5-1 (16.3 MiB 124.0 MiB) (Installed)`.

**Comment by vinceliuice** [comment]
@pschyma I fixed this

**Comment by spsf64** [comment]
@vinceliuice Can you make a new release to comply with latest inkscape for Archlinux Aur?
Thanks

**Comment by vinceliuice** [comment]
No problem!

**Comment by ArchFeh** [comment]
aur updated
