### ISSUE TITLE
glib-compile-resources：command not found

### ISSUE THREAD

**Issue by var-rain** [vinceliuice/Mojave-gtk-theme#143]
./install.sh: line 103: glib-compile-resources：command not found

**Comment by var-rain** [comment]
At the Ubuntu 20.04,the installation script depends on libglib2.0-dev，befor must to be install libglib-2.0-dev,but I did not find it on the README.md,in order to avoid misleading, maybe add one "sudo apt install libglib2.0-dev"

**Comment by var-rain** [comment]
Of course this is just a suggestion.

**Comment by jsmsalt** [comment]
Same in Fedora 32. Need to add `glib2-devel` to **Installation Depends requirement** in README

**Comment by jinva** [comment]
apt-get install libglib2.0-dev-bin
