### ISSUE TITLE
Mojave light doesn't work on visual studio code

### ISSUE THREAD

**Issue by vinliao** [vinceliuice/Mojave-gtk-theme#148]
For some reason, the light theme doesn't work on vscode. Other apps works fine.

![Screenshot from 2020-05-01 18-23-42](https://user-images.githubusercontent.com/34117807/80802243-0bc75b80-8bd9-11ea-9568-e500242af156.png)

The vscode bar is still using Adwaita's theme, while the tweak tool has already been changed to mojave-light.

**Comment by wukongrita** [comment]
Seems fine to me.. (I'm using the compiled version with Inkscape v 1.0 on Fedora 32)

![Screenshot from 2020-05-02 07-44-55](https://user-images.githubusercontent.com/25361005/80850999-1faaa600-8c49-11ea-887a-e2c19ef96153.png)

**Comment by vinliao** [comment]
Reboot solved the issue.

Sometimes a simple reboot works wonder.
