### ISSUE TITLE
Update close, minimize and maximize buttons to match macOS dark mode

### ISSUE THREAD

**Issue by sebdanielsson** [vinceliuice/Mojave-gtk-theme#150]
macOS applies different colors for the close, minimize and maximize buttons depending on if you have light or dark mode activated. For dark mode the colors are slightly more dimmed.

My proposal is to match macOS's color palette which is down below.

Light mode:
Close: #FF605C
Minimize: #FFBD44
Maximize: #00CA4E

Dark mode:
Close: #FF5756
Minimize: #EBBD44
Maximize: #4EC043

**Comment by SebDanielsson** [comment]
No opinions on this?☺️

**Comment by christianbearslyclark** [comment]
> macOS applies different colors for the close, minimize and maximize buttons depending on if you have light or dark mode activated. For dark mode the colors are slightly more dimmed.
> 
> My proposal is to match macOS's color palette which is down below.
> 
> Light mode:
> Close: #FF605C
> Minimize: #FFBD44
> Maximize: #00CA4E
> 
> Dark mode:
> Close: #FF5756
> Minimize: #EBBD44
> Maximize: #4EC043

I need to visualize it tho.
