### ISSUE TITLE
Adding blurring to the translucent backgrounds

### ISSUE THREAD

**Issue by SebDanielsson** [vinceliuice/Mojave-gtk-theme#151]
Is it possible to add blurring to the backgrounds with translucency? Here are some examples on how it looks in macOS and how I've seen other do it in Linux.

https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/translucency/
https://developer.apple.com/documentation/appkit/nsvisualeffectview
https://www.reddit.com/r/gnome/comments/fqkoan/a_demo_with_gnome_apps_using_blur_behind_the/

**Comment by vinceliuice** [comment]
Gnome does not support this, kde plasma have blurring backgrounds
