### ISSUE TITLE
Firefox maximize icon missing and urlbar entity dropdown ui problem

### ISSUE THREAD

**Issue by mrabirahamed** [vinceliuice/Mojave-gtk-theme#152]
I've been using the Mojave-gtk-theme and the Firefox theme quite comfortably for a long time. My PC lost the Firefox Maximize button when the Firefox update came out yesterday and I am having a UI problem with the Entity drop down option in the URL bar. I changed the theme to make sure the Firefox theme had this problem. I will be grateful if you fix it.

Current Firefox - version 77
Screenshot::
![Screenshot from 2020-05-12 20-14-36](https://user-images.githubusercontent.com/34349365/81702778-8a4fb300-948d-11ea-8ff3-0891919318e4.png)

**Comment by vinceliuice** [comment]
Fixed!

**Comment by mrabirahamed** [comment]
thank you

**Comment by vinceliuice** [comment]
You are welcome!
