### ISSUE TITLE
Text in some Gnome Shell panels are transparent

### ISSUE THREAD

**Issue by lfom** [vinceliuice/Mojave-gtk-theme#158]
Hello! It is a nice theme, thanks for your work.

Some text from Gnome Extensions would be invisible, like System-monitor. 

![Screenshot from 2020-05-22 21-42-39](https://user-images.githubusercontent.com/15659999/82717870-5fc3de00-9c75-11ea-8e5d-3216690f01df.png)

Looking that the CSS, I could fix it by changing the color in this block:

```
.popup-menu .popup-inactive-menu-item:insensitive {
  color: transparent;
}
```
Changing the color to \#dede like the block above fixed the problem. Maybe you want to change it too.

Regards

**Comment by lfom** [comment]
Hmm, maybe you did this to remove the first item in the app menu? Once I changed "transparent" to some color, the first item in the app menu wasn't displayed correctly, so I actually changed the colors to something like your Matcha theme:

`color: rgba(222, 222, 222, 0.50);`

And then fixed the app menu too, from:

```
.popup-separator-menu-item {
  height: 0;
  margin: 0;
  padding: 0 0;
  background: none;
  border: none;
}

to

```
.popup-separator-menu-item {
  padding: 0;
  background: none;
  border: none;
}
``
````

**Comment by pawel-szopinski** [comment]
Hello, it's been fixed.
