### ISSUE TITLE
一些奇怪的问题

### ISSUE THREAD

**Issue by inkss** [vinceliuice/Mojave-gtk-theme#161]
操作系统是 Ubuntu 20.04 LTS

![image](https://user-images.githubusercontent.com/31947043/83944156-ee1e8f00-a833-11ea-9541-f8661743b1a6.png)

**Comment by vinceliuice** [comment]
你在这下载最新版安装

**Comment by inkss** [comment]
ok 好像是我配置错误了  20和18似乎有很大的不同
