### ISSUE TITLE
Budgie desktop: raven notifications text color issue

### ISSUE THREAD

**Issue by AXeL-dev** [vinceliuice/Mojave-gtk-theme#163]
![image](https://user-images.githubusercontent.com/30635693/85478147-9dd55a00-b5b3-11ea-8d5c-c351ac2082bb.png)

As seen on the screenshot the text color is grey & almost non visible. I'm using the light variant of the theme. The dark one doesn't have this issue.

Thanks for the pretty theme by the way.

**Comment by vinceliuice** [comment]
![Screenshot from 2020-06-24 09-34-15](https://user-images.githubusercontent.com/7604295/85487156-a56e2080-b5fe-11ea-9cb3-a37796939b7a.png)
Inable the Built-in-theme

**Comment by AXeL-dev** [comment]
> Inable the Built-in-theme

Well, this makes the whole desktop white, which is not the result that i really want to. I've managed to solve it by my own, thanks anyway.
