### ISSUE TITLE
请教一下大神, 主题开发有文档么

### ISSUE THREAD

**Issue by yutent** [vinceliuice/Mojave-gtk-theme#169]
我一直在用linux mint, cinnamon桌面, 目前的主题对它的适配都不是很完整, 我想自己改一下, 又找不到文档。

**Comment by vinceliuice** [comment]
这个不好搞得，都是css3或者scss代码写的，文档一般只有官方的源代码和gtk的控件在css3中类的简介，你要是懂css代码的话可以用lookingglass工具定位cinnamon的控件来调试，你可以按下 "Meta (the Win key) + L" 以触发 Cinnamon Looking Glass

**Comment by yutent** [comment]
原来lookingglass是这个用处, 我一直不知道, 平时都把这个快捷键改成锁屏功能了。
谢谢哈, 有空我试一下
