### ISSUE TITLE
Scaling issue

### ISSUE THREAD

**Issue by nguyennghia9222** [vinceliuice/Mojave-gtk-theme#171]
Hi @vinceliuice,
Thanks for your good work. I just have a small problem with my 4k monitor and scaling at 200%. Please see the picture attachment.
![crop](https://user-images.githubusercontent.com/26781069/91108375-1d5dd300-e6a2-11ea-8d2a-e936d3ea0ec0.png)
![crop](https://user-images.githubusercontent.com/26781069/91108912-86921600-e6a3-11ea-874c-aafacc9f00d4.png)

**Comment by nguyennghia9222** [comment]
I'm on ubuntu 20.04 with gnome 3.36. Thanks

**Comment by vinceliuice** [comment]
Is there any issue on that picture?

**Comment by nguyennghia9222** [comment]
Yes, It just a **hr** length problem. Could we improve the length of the **hr** (I assume that it's css on html element) to make it more perfect.

**Comment by nguyennghia9222** [comment]
Nevermind it. I configured it for myself:
`.popup-separator-menu-item {
  margin: 0;
  padding: 0 0;
  background: none;
  border: none;
  height: 0px;
}

.popup-separator-menu-item .popup-separator-menu-item-separator {
  height: 1px;
  margin: 0 40px;
  background-color: rgba(0, 0, 0, 0);
  padding: 0 0;
}`

**Comment by nguyennghia9222** [comment]
Hide menu separator by modify gnome-shell.css
