### ISSUE TITLE
gdm theme install on Ubuntu20.04

### ISSUE THREAD

**Issue by luv39** [vinceliuice/Mojave-gtk-theme#177]
gdm theme install on Ubuntu20.04, but it's not work.

**Comment by andiub97** [comment]
Me too

**Comment by renffah** [comment]
Got some error messages – i.e. missing _activities-white.svg_ while installing in dark mode or missing files from the _shell-3-28/shell-40-0_ folder (symlinked them) – there was still another error about missing files (maybe I will check their names later).
While I had to reboot my system, gdm was working and the theme looked fine, log in didn't worked. After entering password and login, it went straight back to gdm. Had to revert the gdm theme installation, before I could login.
