### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by chkno** [vinceliuice/Mojave-gtk-theme#178]
The most recent tag is `2020-03-24`, which is 8 months ago.  This version has the [Mojave is 1.5GB and makes GTK apps hang for ~1 minute & allocate 1G of ram while they parse all that CSS problem](https://github.com/vinceliuice/Mojave-gtk-theme/issues/121#issuecomment-601565635) when built with libsass newer than 3.6.1 (and old libsass has security vulnerabilities).

#51 suggests the way to cause new releases is to open an issue requesting them.

Please make a new release.

Thanks!

**Comment by vinceliuice** [comment]
No problem!

**Comment by chkno** [comment]
I see that a `2020-11-29` tag exists now.  Thanks!
