### ISSUE TITLE
nautilus search button right align issue when narrow window

### ISSUE THREAD

**Issue by Gictorbit** [vinceliuice/Mojave-gtk-theme#181]
In the new version of nautilus using this theme, when we narrow the window right margin will appear 
before the latest update everything was ok but as you can see in version `3.38.2` we have this issue

![image](https://user-images.githubusercontent.com/34630603/103646859-9bdf5100-4f6f-11eb-992c-3ce5d3a8b1ba.png)

also, I found this issue in gnome GitLab, this is what they said:

> [https://gitlab.gnome.org/GNOME/nautilus/-/issues/1627](https://gitlab.gnome.org/GNOME/nautilus/-/issues/1627)
the custom theme doesn't support nautilus 3.38. The custom theme is not developed here, so we can't fix it.

so is there any solution to fix this with custom themes?

**Comment by vinceliuice** [comment]
Unless the code of nautilus is modified, the theme cannot modify the structure of the app
