### ISSUE TITLE
Can't create Mojave gdm theme from your source code.

### ISSUE THREAD

**Issue by Tuxman2** [vinceliuice/Mojave-gtk-theme#188]
Hello,

I launched the 'sudo ./install.sh -g' command in the terminal from your source code directory.  The problem is I've got errors.

1. ./install.sh: line 174: prompt : command not found.
./install.sh: line 177: prompt : command not found.

2. /home/manjaro/Documents/Mojave-gtk-theme-master/src/main/gnome-shell/gnome-shell-theme.gresource.xml: The location of "icons/scalable/actions/color-pick.svg" in all source directories failed.

Have you got an idea of the problem ?

Thanks.

Regards.

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed!

**Comment by Tuxman2** [comment]
Thanks a lot. I will test it as soon as possible. ;-)

**Comment by Tuxman2** [comment]
It works, but there is another bug. I create a new subject.
