### ISSUE TITLE
Install script with symlinks

### ISSUE THREAD

**Issue by sandeep-khanna** [vinceliuice/Mojave-gtk-theme#19]
Having git cloned the theme repository, it would be nice to use the installer script to create symlinks to as much of the downloaded content as possible. Doing so, would ensure that all the installed instances of the themes (light, dark, etc) would always have the latest updates when a git pull is performed on the local working directory.

**Comment by vinceliuice** [comment]
But the directories of different users' git projects are not fixed. symlinks can not works on all users' directories.

**Comment by sandeep-khanna** [comment]
I git cloned this repository in my .themes (~/.themes) folder and run the updated install script (all the `cp -ur` commands replaced with ln -sf). Since I am running Ubuntu Mate, I didn't make any changes to the `install_gdm()` function.

With the default destination folder being ~/.themes, the following command creates all the theme variant folders correctly:

`./install.sh -n macOS-Mojave`

Also, updated my copy of the install script to use a different macOS style icon theme:

`IconTheme=la-capitaine-icon-theme`
