### ISSUE TITLE
pad-osd.css file doesn't exist.

### ISSUE THREAD

**Issue by Tuxman2** [vinceliuice/Mojave-gtk-theme#190]
Hi,

Here are the errors messages I received when I installed gtk theme or gdm theme:

/Mojave-gtk-theme-master/src/main/gnome-shell/gnome-shell-theme.gresource.xml:The localization of "pad-osd.css" in all source directories failed.

cp: unable to rate  '/.../Mojave-gtk-theme-master/src/main/gnome-shell/pad-osd.css': No file or folder of this type 

Regards.

**Comment by vinceliuice** [comment]
Fixed!
