### ISSUE TITLE
A few gtk-warnings in Mojave-dark with xfce 4.16.

### ISSUE THREAD

**Issue by darkshram** [vinceliuice/Mojave-gtk-theme#194]
System uses:

- GTK+ 3.24.28
- Glib 2.62.6
- Up to date xfce4 4.16
- Mojave-gtk-theme git 5c5a6c97c3cf8fac5ea563b730e223f16144737e
- Variant: Mojave-dark

A few examples:
```
(xfce4-panel:14069): Gtk-WARNING **: 21:21:45.636: Theme parsing error: gtk.css:9287:102: The :focused pseudo-class is deprecated. Use :focus instead.

(xfce4-panel:14069): Gtk-WARNING **: 21:21:45.636: Theme parsing error: gtk.css:9292:114: The :focused pseudo-class is deprecated. Use :focus instead.

(xfce4-screenshooter:14501): Gtk-WARNING **: 21:22:42.013: Theme parsing error: gtk.css:9287:102: The :focused pseudo-class is deprecated. Use :focus instead.

(xfce4-screenshooter:14501): Gtk-WARNING **: 21:22:42.014: Theme parsing error: gtk.css:9292:114: The :focused pseudo-class is deprecated. Use :focus instead.
```

**Comment by class101** [comment]
Not only xfce, on Cinnamon and McMojave-dark, my .xsession-errors is spammed all over the place of this...

Out of the 12 contributors, nobody can fix this ?????

@vinceliuice @illwieckz @trmdi @alexwaibel @R0b1ns @pawel-szopinski @howyay @Newbytee @Heya @elsiehupp @sburlyaev @miy4mori

**Comment by Newbytee** [comment]
> Not only xfce, on Cinnamon and McMojave-dark, my .xsession-errors is spammed all over the place of this...
> 
> Out of the 12 contributors, nobody can fix this ?????

Please don't mass-ping people like this. We are doing this in our free time — we are contributors because we did something to help this project, not because we signed up to provide user support. I don't use Xfce (or this theme …) and as such I have little incentive to fix this. You can fix it yourself if you want to.
