### ISSUE TITLE
Black background in Budgie DE Linux launcher.

### ISSUE THREAD

**Issue by drk002** [vinceliuice/Mojave-gtk-theme#207]
A black background is visible when the program bar starts. It should be gray like the entire launcher. In other themes it is correct (gray background).
![IMG_20210606_154543](https://user-images.githubusercontent.com/65331799/120936886-9a76a800-c70a-11eb-882a-dddfbd5bd83b.png)

**Comment by vinceliuice** [comment]
I'll fix it!
