### ISSUE TITLE
Close button in overview mode

### ISSUE THREAD

**Issue by balvik** [vinceliuice/Mojave-gtk-theme#21]
Gnome 3.32.0 using Wayland (though same on Xorg), using McMojave Dark for Gnome-shell, McMojave Light for Applications. Taken directly from github master branch.

The window close icon in Overview (Activities) mode don't look right. Please see screenshot. It looks even worse when hovering over it (please see second screenshot while hovering over it). I'm sure it didn't look that bad before Gnome 3.32. If that's how it should look, then feel free to close this issue (though consider making it more visually attractive, since it looks terrible).

![Screenshot from 2019-03-23 22-30-18](https://user-images.githubusercontent.com/36130366/54871908-26b38380-4dbc-11e9-8c7f-fd9421bed408.png)

![Screenshot from 2019-03-23 22-38-06](https://user-images.githubusercontent.com/36130366/54871936-84e06680-4dbc-11e9-98dc-1f12a2c17eac.png)

**Comment by vinceliuice** [comment]
I'll fix this next update

**Comment by balvik** [comment]
Good job, fixed master.
