### ISSUE TITLE
customize primary theme color

### ISSUE THREAD

**Issue by 20NE** [vinceliuice/Mojave-gtk-theme#217]
Appreciation for your work.
It's amazing with installation option `--theme` to Specify primary theme color.
But how to customize primary theme color? 
Like blue theme, how can we modify it's default color value: `#2e7cf7` ?

**Comment by vinceliuice** [comment]
You can change this: https://github.com/vinceliuice/Mojave-gtk-theme/blob/b34d96d81df3f86306bfa05b4f3f272737884cdd/src/sass/_colors-palette.scss#L2

**Comment by 20NE** [comment]
It seems doesn't work.
I change:
```
// Default Blue
$theme_color_default: #5294e2;
 
// Blue
$theme_color_blue: #5294E2;
```
and build it with 
`--theme default`
or
`--theme blue`
all fail, color value still be `#315BEF`

**Comment by vinceliuice** [comment]
Before you install you need compile

**Comment by 20NE** [comment]
Hell yeath !
It's work, Finally !
Cheers !

**Comment by 20NE** [comment]
close it
