### ISSUE TITLE
Tab title looks weird in firefox theme

### ISSUE THREAD

**Issue by Brisolo32** [vinceliuice/Mojave-gtk-theme#229]
When a video/audio is playing the text will go to the right

![image](https://user-images.githubusercontent.com/94653435/185804114-c60675e2-b086-4f7c-9075-c62fa76cf880.png)
^ How it is supposed to look

![image](https://user-images.githubusercontent.com/94653435/185804176-18b90d1a-3635-43d8-880b-de21b7ef1e8b.png)
^ How it looks (ps: i removed the audio playing indicator cuz i dont like it)

**Comment by vinceliuice** [comment]
Fixed!
