### ISSUE TITLE
Completely Transparent Tabs in gnome console

### ISSUE THREAD

**Issue by klascano** [vinceliuice/Mojave-gtk-theme#230]
tabs in gnome console are transparents because it use new widget HdyTabBar

https://gitlab.gnome.org/GNOME/console/-/issues/144

https://github.com/vinceliuice/Qogir-theme/issues/169

![image](https://user-images.githubusercontent.com/5074068/187701033-52f3c502-565d-472c-b915-1d0016a214bb.png)

Please give support.

**Comment by vinceliuice** [comment]
Are you using the last version? I did not find this issue

**Comment by klascano** [comment]
yep, i download the last version available but its tab css is missing

[image: image.png]

Thanks for your help.

**Comment by klascano** [comment]
It's working. 

Thanks!

Great work.
