### ISSUE TITLE
Incomplete libadwaita theme installation for color variants

### ISSUE THREAD

**Issue by nick87720z** [vinceliuice/Mojave-gtk-theme#234]
`./install.sh --libadwaita` works correctly only for theme names without explicit color variant (standard, alt, solid).
For colorized variants it writes (for example - for red):
`cp: cannot stat '.../mojave-gtk-theme-9999/src/assets/gtk/windows-assets/titlebutton-alt-red': No such file or directory`
Resulting theme lacks some elements: window-assets dir seems completely missing and CSD windows (err, if non-csd is ever legal in this domain) - have invisible (unthemed) window buttons (which still works).

**Comment by vinceliuice** [comment]
Fixed now

**Comment by nick87720z** [comment]
Thanks).
