### ISSUE TITLE
Title bar preview is blank/empty on Linux Mint Cinnamon

### ISSUE THREAD

**Issue by AndhikaWB** [vinceliuice/Mojave-gtk-theme#26]
![Screenshot](https://user-images.githubusercontent.com/17119394/55782126-d9caef00-5ad5-11e9-894f-49ec1b185e6f.png)
The real title bar is not affected, only the preview one. Affect all theme variants (light, dark, solid)

**Comment by AndhikaWB** [comment]
Update: The MacOS start menu icon is also not there but I don't know if it is a bug or only achiaveable on non-Cinnamon desktop since there is separate way to apply start menu icon (not using 'Themes' app).

**Comment by vinceliuice** [comment]
This'll fixed, I just not make the preview picture yet

**Comment by AndhikaWB** [comment]
I make a quick fix in case you or somebody else need it. Not so smooth but ok.
![thumbnail](https://user-images.githubusercontent.com/17119394/55951260-066f3a00-5c81-11e9-892a-b7e8370fbf31.png)

**Comment by vinceliuice** [comment]
wow, Thanks!

**Comment by AndhikaWB** [comment]
The dark one
![thumbnail](https://user-images.githubusercontent.com/17119394/55957533-c912a880-5c90-11e9-897d-2abc49130143.png)

**Comment by vinceliuice** [comment]
Fixed now!
