### ISSUE TITLE
Some elements are gray/black colored instead of blue

### ISSUE THREAD

**Issue by AndhikaWB** [vinceliuice/Mojave-gtk-theme#27]
Using Linux Mint 19.1 Cinnamon
![Screenshot](https://user-images.githubusercontent.com/17119394/55783934-b73ad500-5ad9-11e9-8105-5bef1ea651ff.png)
As you can see, the 'Downloads' box is gray/black colored and not blue, also the 'Delete' button box too. Not sure if this is a limitation to Cinnamon desktop. EDIT: using Nemo file manager if that helps.

**Comment by vinceliuice** [comment]
I am designing this way, because you know not all buttons on the mac are a style. so it is easy to distinguish between different types of buttons.

**Comment by AndhikaWB** [comment]
Well, can't blame you for that. But may I know what code to be changed so that the 'Downloads' box and 'Delete' box have a blue color?

**Comment by vinceliuice** [comment]
Delete line 3461 to line 3474 of src/gtk-3.0/sass/_common.scss, then run ./parse-sass.sh then install it

**Comment by vinceliuice** [comment]
I changed the style , now you can try the last one
