### ISSUE TITLE
Text colour issue on Cinnamon desktop notification

### ISSUE THREAD

**Issue by AndhikaWB** [vinceliuice/Mojave-gtk-theme#28]
![Screenshot from 2019-04-11 21-49-55](https://user-images.githubusercontent.com/17119394/55967277-3b40b880-5ca4-11e9-9641-06b1c8336753.png)
As you can see, the "Don't show this message again" text is pretty hard to read. Using Linux Mint 19.1

**Comment by vinceliuice** [comment]
Fixed now
