### ISSUE TITLE
Workspace applet text colour issue on Cinnamon desktop

### ISSUE THREAD

**Issue by AndhikaWB** [vinceliuice/Mojave-gtk-theme#29]
![Screenshot](https://user-images.githubusercontent.com/17119394/56011693-fd2ead80-5d12-11e9-96ce-18f522bbfe1d.png)
The "1 2 3 4" text colour is almost unreadable. Note that I moved the panel to the top, on Linux OS fresh install, the desktop panel location is on the bottom.

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Can you tell me your desktop version?

**Comment by vinceliuice** [comment]
Fixed now!
