### ISSUE TITLE
Dark theme text colour issue on Chromium bottom download history

### ISSUE THREAD

**Issue by AndhikaWB** [vinceliuice/Mojave-gtk-theme#30]
![Screenshot from 2019-04-14 18-50-49](https://user-images.githubusercontent.com/17119394/56092467-ab3e8100-5ee6-11e9-9a9d-dc3671af68d6.png)
Not sure this is an issue with Chromium itself or the theme, but seems like other dark themes are causing this issue as well.

**Comment by vinceliuice** [comment]
This has appeared since the Chromium > 73

**Comment by hz61p1** [comment]
I can confirm this issue too.

**Comment by mibradev** [comment]
It's a Chromium bug: [945987](https://bugs.chromium.org/p/chromium/issues/detail?id=945987&q=gtk%20dark%20theme&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

**Comment by vinceliuice** [comment]
The last version of Chrome fixed it
