### ISSUE TITLE
[Help Needed] A way to revert GDM theme

### ISSUE THREAD

**Issue by KennFatt** [vinceliuice/Mojave-gtk-theme#32]
Hello,

I just installed the theme with gdm option enabled. Everything is fine and good. But, I want to revert to the default theme (Ubuntu 19.04) and there is no option available on `install.sh`.

I've tried to read the code from `install.sh` and try to revert it, it makes me kinda confused (I'm not familiar with GDM theme and never touched it before).

And now I'm **looking for help** to make my GDM theme back with factory configuration.

Thank you.

**Comment by vinceliuice** [comment]
OK, I'll give this option soon

**Comment by vinceliuice** [comment]
Now you can use sudo ./install -r to revert gdm theme
