### ISSUE TITLE
Gnome terminal doesn't restore to normal size after unmaximizing window (PopOS 19.04)

### ISSUE THREAD

**Issue by huylenguyen806** [vinceliuice/Mojave-gtk-theme#35]
![Screenshot from 2019-05-16 01-56-48](https://user-images.githubusercontent.com/28498441/57801650-5e1c2c00-777e-11e9-9f57-2bb66587172b.png)
Other themes don't have this issue, can you please fix it? :(
Sorry for my bad english.

**Comment by vinceliuice** [comment]
Fixed now!
