### ISSUE TITLE
How do you install GDM theme?

### ISSUE THREAD

**Issue by truvaking** [vinceliuice/Mojave-gtk-theme#37]
Hello,

I apologize in advance if this question is a bit dumb.

I don't really know how to install the GDM theme. I ran `./install.sh -g` but all I get is a `Done` message.

I've looked at more complex method but it seems pretty hard to change the GDM manually.

Please help?

Best regards,

**Comment by vinceliuice** [comment]
Did you run it in with sudo?

**Comment by truvaking** [comment]
I did not. Thank you

**Comment by truvaking** [comment]
sorry to bother again... the background image image during logon isn't the blurred image like in the preview but instead a plain gray color... what is needed to be done to have it exactly like the preview?

**Comment by truvaking** [comment]
never mind, i was editing the wrong css file

**Comment by widhitl** [comment]
how did you fix it? i have same problem with it, but i already install with sudo ./install.sh -g

before applying this theme, i tried some gdm theme from gnome-look but the login screen still plain gray color, i tried to manually edit /etc/gdm3/greeter.dconf-defaults as root https://wiki.debian.org/GDM#Customizing_the_GDM_appearance but it still plain gray

**Comment by truvaking** [comment]
try modifying `/usr/share/gnome-shell/theme/ubuntu.css`

**Comment by widhitl** [comment]
what to check on that file?

**Comment by truvaking** [comment]
you want to change the background image? 

look for `#lock` it should be something like lockDialogGroup

**Comment by widhitl** [comment]
![image](https://user-images.githubusercontent.com/12552542/68078233-62a7d000-fe04-11e9-967a-ecd7f4be351a.png)

its default setting from this theme, but it is located at /usr/share/theme/Mojave-light/gnome-shell/gnome-shell.css

on every theme is same gnome-shell css. the different is on assett folder ond background image

should i copy gnome-shell.css to/usr/share/gnome-shell/theme/gnome-shell.css or not? or i copy as /usr/share/gnome-shell/theme/debian.css

**Comment by truvaking** [comment]
I think you should change `/usr/share/gnome-shell/theme/debian.css`
