### ISSUE TITLE
大佬可以问下怎么修改应用最大化后也顶栏的间距吗

### ISSUE THREAD

**Issue by Yakumo-Yukari** [vinceliuice/Mojave-gtk-theme#4]
![2018-11-30 20 41 48](https://user-images.githubusercontent.com/12076232/49292736-0c8e2680-f4e9-11e8-99b8-31c05e0e585d.png)

现在使用的系统是elementary os   使用Mojave后应用最大化后和顶栏的间距有点大

**Comment by vinceliuice** [comment]
注销一下就可以了

**Comment by Yakumo-Yukari** [comment]
@vinceliuice  好的~
