### ISSUE TITLE
No transparency in Nautilus (XFCE)

### ISSUE THREAD

**Issue by clementpoiret** [vinceliuice/Mojave-gtk-theme#40]
Hi,

I'm on Manjaro under XFCE. I replaced Thunar by Nautilus but in Light or Dark theme, the left panel of nautilus is always black without transparency. Have I done something wrong? 

![IMG](https://imgur.com/RTm0Hb0l.png)
![IMG](https://imgur.com/OH3Gra8l.png)

Thanks.

**Comment by vinceliuice** [comment]
I'll check this on my manjaro

**Comment by vinceliuice** [comment]
That's wired, nautilus use csd windows not xfwm4 on my manjaro, so I don't have this issue

**Comment by clementpoiret** [comment]
So do you know how can I solve this issue?

**Comment by vinceliuice** [comment]
Sorry! I also don't know how to do with this.
