### ISSUE TITLE
How to apply GDM theme?

### ISSUE THREAD

**Issue by dscamargo** [vinceliuice/Mojave-gtk-theme#41]
Hello,

I installed my theme using `sudo ./install.sh -g` and apply theme succesfully in system.

But in login screen, this theme is not applied, how to do this?

**Comment by vinceliuice** [comment]
What's your system? are you using gdm or lightdm?

**Comment by dscamargo** [comment]
Ubuntu 19.04.
I'm using gdm.

**Comment by vinceliuice** [comment]
This theme is not working on lock screen, but login screen should be ok

**Comment by dscamargo** [comment]
Login screen should be work only using `./instal.sh -g`   ?

**Comment by vinceliuice** [comment]
Yes, sudo ./install.sh -g should works on ubuntu 19.04

**Comment by vinceliuice** [comment]
I'll test it

**Comment by dscamargo** [comment]
I reinstalled theme now and is working in login screen.

Thank you.
