### ISSUE TITLE
Weird flickering in Firefox tab bar when hovered over the close tab button

### ISSUE THREAD

**Issue by a2chan** [vinceliuice/Mojave-gtk-theme#43]
![ezgif-1-5c8055e5236e](https://user-images.githubusercontent.com/46082775/61482593-9e836a80-a9b8-11e9-84b0-74556629b0eb.gif)

OS: Ubuntu 19.04
Firefox version: 68.0

**Comment by bruno-anjos** [comment]
+1 on this problem

**Comment by vinceliuice** [comment]
Does this issue occur in only one tap too，or multiple tags?

**Comment by bruno-anjos** [comment]
For me this issue occurs specifically when you have more than one tab open and you have one tab selected (it can't be the last) and try to hover over the arrow that appears in the top right corner near the close button to close the last tab

**Comment by dr3mro** [comment]
As I found it is not related to the theme but to firefox only if you moved the new tab button to the titlebar this is not a theme bug

**Comment by trmdi** [comment]
The issue disappears when I comment this line:
https://github.com/vinceliuice/Mojave-gtk-theme/blob/c446392962c3e370a0d3d4709228cb28236d08fb/src/firefox/chrome/Mojave/parts/tabsbar.css#L235

But I don't know if there is a side effect. Can you have a look at this? @vinceliuice

**Comment by dr3mro** [comment]
Do you have the same issue when click on menu then move window the menu refuses to come again!?!?!?

Amr Osman,MD
