### ISSUE TITLE
Google Chrome title bar height in application mode

### ISSUE THREAD

**Issue by rmoravcik** [vinceliuice/Mojave-gtk-theme#49]
Hi all,

do you have any idea how to fix Google Chrome title bar height in application mode?

![Snímka obrazovky z 2019-08-31 11-29-38](https://user-images.githubusercontent.com/2954118/64062094-11e8e080-cbe3-11e9-966a-3586b500c2df.png)

Thank you,
Roman

**Comment by vinceliuice** [comment]
No if you change this, all non-csd apps' titlebar will change
