### ISSUE TITLE
大佬发现个问题，更新主题后定栏变小了，我对比了下默认主题后发现缩小了蛮多的

### ISSUE THREAD

**Issue by Yakumo-Yukari** [vinceliuice/Mojave-gtk-theme#5]
默认主题

![2018-12-05 16 02 46](https://user-images.githubusercontent.com/12076232/49499002-d6192880-f8a7-11e8-9960-8d691bf09d77.png)

Mojave主题

![2018-12-05 16 03 03](https://user-images.githubusercontent.com/12076232/49499020-e5987180-f8a7-11e8-8359-24463be8f51f.png)

定栏和默认主题的大小不一样 左边图标和字体都挤到一起了

需要在哪里修改定栏的大小呢？

**Comment by Yakumo-Yukari** [comment]
系统是 elementary os

**Comment by vinceliuice** [comment]
我调整了一下: 
![2018-12-05 17-41-15](https://user-images.githubusercontent.com/7604295/49504626-061af880-f8b5-11e8-9ff1-a718cad9df07.png)
你再试试

**Comment by vinceliuice** [comment]
自己想修改的话就修改截图位置:
![2018-12-05 17-42-19](https://user-images.githubusercontent.com/7604295/49504695-2e0a5c00-f8b5-11e8-849e-77efb7813e6b.png)
在: /src/gtk-3.0/sass/_applications.scss 里,  > revealer label 是文字,  > revealer image 是图标

**Comment by Yakumo-Yukari** [comment]
@vinceliuice 好的  谢谢了

**Comment by vinceliuice** [comment]
不客气
