### ISSUE TITLE
Cinnamon DE: No "Menu" button displayed

### ISSUE THREAD

**Issue by spsf64** [vinceliuice/Mojave-gtk-theme#50]
I use cinnamon DE and the "menu" button is not displayed.
If I click on it, where it is supposed to be, it works as expected.
See attached images:

These 2 are Mojave-dark, no menu button:
![1Mojave-dark](https://user-images.githubusercontent.com/1877391/64199401-a14ef780-ce60-11e9-9d06-bd2f6dca199d.png)
![3Mojave-dark](https://user-images.githubusercontent.com/1877391/64200116-34d4f800-ce62-11e9-88c3-8d16a14e35af.png)

These are with Plata Theme, the menu button displayed at top left:
![1Plata](https://user-images.githubusercontent.com/1877391/64199414-a7dd6f00-ce60-11e9-9b92-78522cb6fa89.png)
![3Plata](https://user-images.githubusercontent.com/1877391/64200157-44ecd780-ce62-11e9-8324-7e89ff9c5da3.png)

**Comment by granitepenguin** [comment]
I'm seeing the same thing.  I tried different placements, too; it doesn't matter if on left or right.

**Comment by vinceliuice** [comment]
I'll fix this, 'll add menu icon

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by granitepenguin** [comment]
confirmed; looks great.  Thanks!

**Comment by vinceliuice** [comment]
That's all right!

**Comment by spsf64** [comment]
> Fixed now!
Thank you!!!
Working perfectly here!
