### ISSUE TITLE
Wired background in GNOME

### ISSUE THREAD

**Issue by sapjunior** [vinceliuice/Mojave-gtk-theme#58]
I encounter wired menu background and not sure where does the problem come from. The problem will occur when I used mojave series shell themes (both light and dark). I'm running Arch Linux with latest update (as today gnome3.34) on xps9370 4k model. Here are the pictures.

![Screenshot from 2019-10-06 13-00-28](https://user-images.githubusercontent.com/987946/66265026-a2958a80-e839-11e9-9674-3b6321e6ae24.png)

![Screenshot from 2019-10-06 13-00-24](https://user-images.githubusercontent.com/987946/66265030-b0e3a680-e839-11e9-9324-ad7982eace9e.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by sapjunior** [comment]
Thank you so much! Everything work perfectly

**Comment by vinceliuice** [comment]
That's all right!
