### ISSUE TITLE
在次麻烦大佬，请教下这个位置的背景透明度在那个位置修改

### ISSUE THREAD

**Issue by Yakumo-Yukari** [vinceliuice/Mojave-gtk-theme#6]
![2018-12-10 11 34 36](https://user-images.githubusercontent.com/12076232/49709536-d03c9200-fc6f-11e8-9114-40a65c6e9819.png)

想修改成半透明，大佬可以实现吗？需要修改哪里？

**Comment by vinceliuice** [comment]
![2018-12-10 12-25-28](https://user-images.githubusercontent.com/7604295/49710810-cbc7a780-fc76-11e8-88ad-20bca32d4d09.png)
截图位置popover后面添加:
background-color: rgba($_popover_bg, 0.5);   0.5就是50%透明, 0是全透明
