### ISSUE TITLE
Firefox hover tabs will cause a glitch

### ISSUE THREAD

**Issue by dr3mro** [vinceliuice/Mojave-gtk-theme#61]
Oopen firefox after apply the theme to firefox and then open at least 2 tabs then make the left one active then hover over the right tab close button but dont click it you will see the glitch

**Comment by vinceliuice** [comment]
Could you tell me you system version and firefox version, I don't have this issue

**Comment by dr3mro** [comment]
I use Arch linux Gnome 3.34.1 Linux kernel 5.3.5

**Comment by vinceliuice** [comment]
Firefox version?

**Comment by dr3mro** [comment]
Firefox 69.0.3 
I found it 
its due to moving new tab button to title bar 
only happens when right most tab is not active and hover over close button
restoring new tab button to tab bar will fix this

**Comment by bruno-anjos** [comment]
This is exactly what i experienced in #43

**Comment by trmdi** [comment]
@dr3mro Could you please try the fix in #43 and confirm this is fixed by close this issue ?
Thank you!

**Comment by dr3mro** [comment]
As soon I come to my PC I will try ISA and report back 

Amr Osman,MD

**Comment by dr3mro** [comment]
solved
