### ISSUE TITLE
Sidebar, menu, transparency does not work

### ISSUE THREAD

**Issue by abarajithan11** [vinceliuice/Mojave-gtk-theme#64]
I'm using Ubuntu 16.04 with Unity. After downloading, running the ./install sh and selecting the theme through Ubuntu Tweak Tool, I get the following appearance.

![image](https://user-images.githubusercontent.com/26372005/66754940-98513d00-ee86-11e9-8f1f-081e15c2aba7.png)

**Comment by vinceliuice** [comment]
Sorry! this theme does not support old system before ubuntu18.10
