### ISSUE TITLE
Falto agregar 2 hovers --- Me encanta el tema.

### ISSUE THREAD

**Issue by marfer1** [vinceliuice/Mojave-gtk-theme#67]
**Falto agregar 2 hovers se puede resolver asi.**

### **Abrir folder**: /home/USER/.mozilla/firefox/<folder>.default/chrome/Mojave/parts/popups.css

Y Agregar lo siguiente:

```
menu:hover{
       background: rgba(41, 145, 255, 1)!important;
}
```

```
menuitem:hover{
	background: rgba(41, 145, 255, 1)!important;
}
```

**Comment by vinceliuice** [comment]
Thanks! I'll add this to my theme

**Comment by vinceliuice** [comment]
Fixed!
