### ISSUE TITLE
icon overlayed when search app

### ISSUE THREAD

**Issue by widhitl** [vinceliuice/Mojave-gtk-theme#68]
icon overlayed when search only. on all shell (debian 10)
![image](https://user-images.githubusercontent.com/12552542/68041256-c3e77a80-fd02-11e9-9115-9b8a8d59c303.png)

**Comment by vinceliuice** [comment]
Could you tell me your gnome shell version

**Comment by widhitl** [comment]
3.30.2

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/Mojave-gtk-theme/releases/tag/2019-09-09

**Comment by vinceliuice** [comment]
You can download this and try, the last one on github I'll updated for gnome 3.34

**Comment by widhitl** [comment]
![image](https://user-images.githubusercontent.com/12552542/68078308-2aa18c80-fe06-11e9-892a-626feba12a7d.png)

cool. its work, thanks

**Comment by vinceliuice** [comment]
That's ok!
