### ISSUE TITLE
大佬我修改了透明度后，删除主题重新执行./install.sh安装后背景还是没有改变呢

### ISSUE THREAD

**Issue by Yakumo-Yukari** [vinceliuice/Mojave-gtk-theme#7]
![2018-12-10 15 27 10](https://user-images.githubusercontent.com/12076232/49716956-4fda5900-fc90-11e8-905b-f338a1d0f746.png)
根据大佬的提示。在 popover 里面增加了代码重新安装后没效果呢 是不是我哪里弄错了

**Comment by vinceliuice** [comment]
需要先执行./parse-sass.sh 重新编译css文件 (需要安装sassc), 然后执行安装脚步

**Comment by Yakumo-Yukari** [comment]
@vinceliuice emmmm  好吧 我蠢了    谢谢大佬耐心解答

**Comment by vinceliuice** [comment]
哈哈,不客气
