### ISSUE TITLE
Themes Working Not Correct Ubuntu 16.04

### ISSUE THREAD

**Issue by thanhtd-1444** [vinceliuice/Mojave-gtk-theme#76]
I try to install in Ubuntu 16.04, It looks not good.
![Screenshot from 2019-11-19 10-52-47](https://user-images.githubusercontent.com/49387853/69115330-c09e0e00-0aba-11ea-8971-34123898774f.png)

**Comment by vinceliuice** [comment]
It doesn't support this theme, you should install at least ubuntu 18.04
