### ISSUE TITLE
Firefox Menu issue

### ISSUE THREAD

**Issue by dr3mro** [vinceliuice/Mojave-gtk-theme#79]
whenever I launch firefox and click on menu it shows correctly then if I resized the firefox window or moved it the menu wont show any more except after restart firefox
using latest version of Mojave Gtk Theme from git on fully updated arch linux install + gnome shell

**Comment by dr3mro** [comment]
I have tried vanilla firefox and it works and this issue is mojave theme specific

**Comment by dr3mro** [comment]
I have made a video to demonstrate the issue i am having 
https://youtu.be/IFS7xNx6oMk

**Comment by dr3mro** [comment]
I have found out that changing this line fixing the issue above
please consider apply this fix to master

`diff --git a/src/firefox/chrome/Mojave/parts/popups.css b/src/firefox/chrome/Mojave/parts/popups.css
index 693de03..379eafa 100644
--- a/src/firefox/chrome/Mojave/parts/popups.css
+++ b/src/firefox/chrome/Mojave/parts/popups.css
@@ -68,7 +68,7 @@ panel:not(.tooltip-xul-wrapper) .panel-arrowcontent {
 	border: 1px solid !important;
 	border-color: var(--gnome-popover-border-color) !important;
 	border-radius: 9px;
-	box-shadow: var(--gnome-popover-shadow) !important;
+	box-shadow: var(--gnome-popover-shadow);
 	padding: 8px 12px !important;
 	color: var(--gnome-toolbar-color) !important;
 }`

**Comment by vinceliuice** [comment]
You mean remove the "!important" after "box-shadow: var(--gnome-popover-shadow)" can fix this?

**Comment by dr3mro** [comment]
Yes that what fixed it 
Any way I don’t see shadows any where on my theme and I don’t know why shadows don’t work on arch Linux gnome with your theme

**Comment by vinceliuice** [comment]
OK,  I removed it.

**Comment by dr3mro** [comment]
The firefox menu bug came back 
launch firefox 
click menu 
resize window
click again on menu 
nothing
