### ISSUE TITLE
大佬在问下，主题的右键菜单背景颜色怎么修改

### ISSUE THREAD

**Issue by Yakumo-Yukari** [vinceliuice/Mojave-gtk-theme#8]
![2018-12-12 08 47 26](https://user-images.githubusercontent.com/12076232/49839612-d0ad6800-fdea-11e8-825b-6838d9da40c0.png)
想把右键菜单也改成半透明的，大佬有空了帮忙看看 谢谢了

**Comment by vinceliuice** [comment]
![2018-12-12 12-35-11](https://user-images.githubusercontent.com/7604295/49847889-593d0000-fe0d-11e8-8dbd-a8477b76aa9e.png)
修改成:
@if $transparency == 'true' { $_menu_bg: if($variant=='light', rgba($base_color, 0.5), rgba($bg_color, 0.5)); }
就是一半透明度

**Comment by Yakumo-Yukari** [comment]
@vinceliuice 2333   谢谢大佬
