### ISSUE TITLE
Cant install icon 'debian' cause ',' on line 23 in install.sh

### ISSUE THREAD

**Issue by R0b1ns** [vinceliuice/Mojave-gtk-theme#81]
install.sh
linenumber 23

Pls remove the ','
ICON_VARIANTS=('' '-normal' '-gnome' '-ubuntu' '-arch' '-manjaro' '-fedora' '-debian', '-void')

to

ICON_VARIANTS=('' '-normal' '-gnome' '-ubuntu' '-arch' '-manjaro' '-fedora' '-debian' '-void')

Greets ;)

**Comment by vinceliuice** [comment]
Thanks! I'll fix this, didn't notice that before

**Comment by vinceliuice** [comment]
Fixed!
