### ISSUE TITLE
Close, Minimize and Maximize button on the Tab Bar

### ISSUE THREAD

**Issue by przerada** [vinceliuice/Mojave-gtk-theme#83]
Hi, after update firefox close, minimize and maximize button goes down to the Tab Bar

![Zrzut ekranu z 2019-12-04 09-18-49](https://user-images.githubusercontent.com/27885074/70125611-6b93f780-1677-11ea-8088-0549d55e990e.png)

How to change that?

**Comment by roberChen** [comment]
Same thing happens to me!

**Comment by vinceliuice** [comment]
Did you use the last update on github? I fixed this issue @roberChen

**Comment by spsf64** [comment]
Can you make a new release?
So the archlinux/aur package can be updated.
Thanks

**Comment by vinceliuice** [comment]
No problem! @spsf64
