### ISSUE TITLE
Budgie panel is not transparent even when chosen transparent in settings

### ISSUE THREAD

**Issue by gsbhasin123** [vinceliuice/Mojave-gtk-theme#86]
In budgie desktop settings i chose panel as always transparent but with this theme it isn't. It is with your other themes (Qogir, Canta, ChromeOS)... and with my themes. Pls fix

**Comment by gsbhasin123** [comment]
@vinceliuice  can you fix this

**Comment by vinceliuice** [comment]
I updated this theme, you can try the last update here

**Comment by gsbhasin123** [comment]
Indeed fixed
