### ISSUE TITLE
[Feature request] Unison hovering effect for Firefox window control buttons

### ISSUE THREAD

**Issue by trmdi** [vinceliuice/Mojave-gtk-theme#87]
I'm talking about this:
![img](https://user-images.githubusercontent.com/11857205/69910106-5b420980-1438-11ea-8c90-b278958934d2.gif)
When you're hovering on any button, all other ones would also display their symbols at the same time.
Is it possible for Firefox?
(This is how macOS buttons work. You can ignore the animation effect.)

**Comment by vinceliuice** [comment]
Sorry, firefox theme don't support this

**Comment by trmdi** [comment]
Couldn't we change from: `parent > button:hover` to: `parent:hover > button`?
Just an idea.
