### ISSUE TITLE
[New icon request] Firefox window control buttons for the inactive hovering state

### ISSUE THREAD

**Issue by trmdi** [vinceliuice/Mojave-gtk-theme#89]
Currently, in Firefox, there are no close/min/max icons for the inactive hovering state, could you please add them?

**Comment by vinceliuice** [comment]
No problem!

**Comment by trmdi** [comment]
Hi, I've seen you added it in a new commit. But the buttons in the inactive hovering state don't have color.
They should be like this:

![ezgif-1-f5b936deb522](https://user-images.githubusercontent.com/11857205/70842920-621b4400-1e5c-11ea-9b57-2eda2a36abb6.gif)

**Comment by vinceliuice** [comment]
Thanks！I get this， I'll update this
