### ISSUE TITLE
非常好看，如果能够调大窗口阴影深度就更加好了哈

### ISSUE THREAD

**Issue by Hoking007** [vinceliuice/Mojave-gtk-theme#94]
非常好看，如果能够调大窗口阴影深度就更加好了哈
我很喜欢你的主题，但是在gnome-look看到的截图，窗口阴影比较好看，但是在我的manjaro（gnome 3.34）上窗口阴影很淡，我很喜欢那种厚重的窗口阴影，请问如何调整呢？或者可否增加厚重窗口阴影的选择？

**Comment by vinceliuice** [comment]
好的,我调整一下

**Comment by Hoking007** [comment]
> 好的,我调整一下

非常感谢作者的回复，已经加星关注！
